CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS mart;

CREATE TABLE IF NOT EXISTS raw.products_raw (
    id BIGSERIAL PRIMARY KEY,
    loaded_at TIMESTAMP DEFAULT NOW(),
    payload JSONB
);